"""Unit tests for Algorithms and Data Structures 1 AI - Binary Search Trees."""
import sys

from typing import Any, NamedTuple
import pytest

from bst import BinarySearchTree, TreeNode


#region Helper stuff and test data

try:
    from conftest import points  # type: ignore
except ImportError:

    def points(points: float):
        return lambda function: function


def create_list_from_file(filename: str) -> list[int]:
    with open(filename, 'r') as fp:
        list_ = []
        for item in fp:
            list_.append(int(item))
    return list_



def visualize_tree(tree_root: TreeNode | None) -> str:
    """Kudos for this horrible, but greatly working mess.
    
    J.V.
    https://stackoverflow.com/questions/34012886/print-binary-tree-level-by-level-in-python
    """
    if tree_root is not None:
        ret_str = "\n"
        lines, *_ = display_aux(tree_root)
        for line in lines:
            ret_str += line + "\n"
            # print(line)
        return ret_str + "\n"
    else:
        return ""

def display_aux(cur_node: TreeNode) -> tuple[list[str], int, int, int]:
    """Returns list of strings, width, height, and horizontal coordinate of the root."""
    # No child.
    if cur_node.right is None and cur_node.left is None:
        line = '%s' % cur_node.key
        width = len(line)
        height = 1
        middle = width // 2
        return [line], width, height, middle

    # Only left child.
    if cur_node.right is None:
        lines, n, p, x = display_aux(cur_node.left) # type: ignore
        s = '%s' % cur_node.key
        u = len(s)
        first_line = (x + 1) * ' ' + (n - x - 1) * '_' + s
        second_line = x * ' ' + '/' + (n - x - 1 + u) * ' '
        shifted_lines = [line + u * ' ' for line in lines]
        return [first_line, second_line] + shifted_lines, n + u, p + 2, n + u // 2

    # Only right child.
    if cur_node.left is None:
        lines, n, p, x = display_aux(cur_node.right)
        s = '%s' % cur_node.key
        u = len(s)
        first_line = s + x * '_' + (n - x) * ' '
        second_line = (u + x) * ' ' + '\\' + (n - x - 1) * ' '
        shifted_lines = [u * ' ' + line for line in lines]
        return [first_line, second_line] + shifted_lines, n + u, p + 2, u // 2

    # Two children.
    left, n, p, x = display_aux(cur_node.left)
    right, m, q, y = display_aux(cur_node.right)
    s = '%s' % cur_node.key
    u = len(s)
    first_line = (x + 1) * ' ' + (n - x - 1) * '_' + s + y * '_' + (m - y) * ' '
    second_line = x * ' ' + '/' + (n - x - 1 + u + y) * ' ' + '\\' + (m - y - 1) * ' '
    if p < q:
        left += [n * ' '] * (q - p)
    elif q < p:
        right += [m * ' '] * (p - q)
    zipped_lines = zip(left, right)
    lines = [first_line, second_line] + [a + u * ' ' + b for a, b in zipped_lines]
    return lines, n + m + u, max(p, q) + 2, n + u // 2

class TreeSolution(NamedTuple):
    """Captures a tree structure, size and orderings to compare to."""
    insertion_order: list[tuple[int, Any]]
    inorder: list[TreeNode]
    preorder: list[TreeNode]
    postorder: list[TreeNode]
    size: int
    root: TreeNode

@points(0)
def test_python_version():
    assert sys.version_info >= (3, 13), \
        f"Python version is too low. Required >=3.13, your version: {sys.version_info.major}.{sys.version_info.minor}"

@pytest.fixture
def tree_1() -> TreeSolution:
    # Autogenerated with 'create_testcase.print_code_defining_solution'
    # [10, 5, 12, 3]
    key_to_node: dict[int, TreeNode] = {
        10: TreeNode(10, '10'),
        5: TreeNode(5, '5'),
        12: TreeNode(12, '12'),
        3: TreeNode(3, '3'),
    }

    root = key_to_node[10]
    root.left = key_to_node[5]
    root.right = key_to_node[12]
    root.left.left = key_to_node[3]

    key_to_node[3].overwrite_parent(key_to_node[5])
    key_to_node[5].overwrite_parent(key_to_node[10])
    key_to_node[10].overwrite_parent(None)
    key_to_node[12].overwrite_parent(key_to_node[10])

    inorder = [
        key_to_node[3],
        key_to_node[5],
        key_to_node[10],
        key_to_node[12],
    ]

    preorder = [
        key_to_node[10],
        key_to_node[5],
        key_to_node[3],
        key_to_node[12],
    ]

    postorder = [
        key_to_node[3],
        key_to_node[5],
        key_to_node[12],
        key_to_node[10],
    ]

    insertion_order = [
        (10, '10'),
        (5, '5'),
        (12, '12'),
        (3, '3'),
    ]

    return TreeSolution(
        insertion_order = insertion_order,
        inorder = inorder,
        preorder = preorder,
        postorder = postorder,
        size = 4,
        root = root
    )

@pytest.fixture
def tree_2() -> TreeSolution:
    # Autogenerated with 'create_testcase.print_code_defining_solution'
    # [5, 18, 1, 8, 14, 16, 13, 3]
    key_to_node: dict[int, TreeNode] = {
        5: TreeNode(5, '5'),
        18: TreeNode(18, '18'),
        1: TreeNode(1, '1'),
        8: TreeNode(8, '8'),
        14: TreeNode(14, '14'),
        16: TreeNode(16, '16'),
        13: TreeNode(13, '13'),
        3: TreeNode(3, '3'),
    }

    root = key_to_node[5]
    root.left = key_to_node[1]
    root.right = key_to_node[18]
    root.left.right = key_to_node[3]
    root.right.left = key_to_node[8]
    root.right.left.right = key_to_node[14]
    root.right.left.right.left = key_to_node[13]
    root.right.left.right.right = key_to_node[16]

    key_to_node[1].overwrite_parent(key_to_node[5])
    key_to_node[3].overwrite_parent(key_to_node[1])
    key_to_node[5].overwrite_parent(None)
    key_to_node[8].overwrite_parent(key_to_node[18])
    key_to_node[13].overwrite_parent(key_to_node[14])
    key_to_node[14].overwrite_parent(key_to_node[8])
    key_to_node[16].overwrite_parent(key_to_node[14])
    key_to_node[18].overwrite_parent(key_to_node[5])

    inorder = [
        key_to_node[1],
        key_to_node[3],
        key_to_node[5],
        key_to_node[8],
        key_to_node[13],
        key_to_node[14],
        key_to_node[16],
        key_to_node[18],
    ]

    preorder = [
        key_to_node[5],
        key_to_node[1],
        key_to_node[3],
        key_to_node[18],
        key_to_node[8],
        key_to_node[14],
        key_to_node[13],
        key_to_node[16],
    ]

    postorder = [
        key_to_node[3],
        key_to_node[1],
        key_to_node[13],
        key_to_node[16],
        key_to_node[14],
        key_to_node[8],
        key_to_node[18],
        key_to_node[5],
    ]

    insertion_order = [
        (5, '5'),
        (18, '18'),
        (1, '1'),
        (8, '8'),
        (14, '14'),
        (16, '16'),
        (13, '13'),
        (3, '3'),
    ]

    return TreeSolution(
        insertion_order = insertion_order,
        inorder = inorder,
        preorder = preorder,
        postorder = postorder,
        size = 8,
        root = root
    )

@pytest.fixture
def trees_while_deleting(tree_2: TreeSolution) -> tuple[TreeSolution, list[tuple[int, TreeNode | None]]]:
    # Autogenerated with 'create_testcase.print_deletion_sequence'
    root_0 = TreeNode(8, '8')
    root_0.left = TreeNode(1, '1')
    root_0.right = TreeNode(18, '18')
    root_0.left.right = TreeNode(3, '3')
    root_0.right.left = TreeNode(14, '14')
    root_0.right.left.left = TreeNode(13, '13')
    root_0.right.left.right = TreeNode(16, '16')

    root_1 = TreeNode(8, '8')
    root_1.left = TreeNode(1, '1')
    root_1.right = TreeNode(18, '18')
    root_1.left.right = TreeNode(3, '3')
    root_1.right.left = TreeNode(16, '16')
    root_1.right.left.left = TreeNode(13, '13')

    root_2 = TreeNode(13, '13')
    root_2.left = TreeNode(1, '1')
    root_2.right = TreeNode(18, '18')
    root_2.left.right = TreeNode(3, '3')
    root_2.right.left = TreeNode(16, '16')

    root_3 = TreeNode(13, '13')
    root_3.left = TreeNode(1, '1')
    root_3.right = TreeNode(18, '18')
    root_3.left.right = TreeNode(3, '3')

    root_4 = TreeNode(18, '18')
    root_4.left = TreeNode(1, '1')
    root_4.left.right = TreeNode(3, '3')

    root_5 = TreeNode(18, '18')
    root_5.left = TreeNode(3, '3')

    root_6 = TreeNode(3, '3')

    root_7 = None

    deletion_sequence: list[tuple[int, TreeNode | None]] = [
        (5, root_0),
        (14, root_1),
        (8, root_2),
        (16, root_3),
        (13, root_4),
        (1, root_5),
        (18, root_6),
        (3, root_7),
    ]

    return tree_2, deletion_sequence

#endregion

@points(0.5)
def test_simple_insert(tree_1: TreeSolution):
    bst = BinarySearchTree()
    for insert in tree_1.insertion_order:
        bst.insert(*insert)

    assert bst.root == tree_1.root, (
        "Got wrong tree after inserting a few values.\n"
        f"Expected: {visualize_tree(tree_1.root)}"
        f"Got: {visualize_tree(bst.root)}"
    )
    tree_1.root.left = None
    assert bst.root != tree_1.root

@points(1)
def test_insert(tree_2: TreeSolution):    
    bst = BinarySearchTree()
    for insert in tree_2.insertion_order:
        bst.insert(*insert)

    assert bst.root == tree_2.root, (
        "Got wrong tree after inserting a few values.\n"
        f"Expected: {visualize_tree(tree_2.root)}"
        f"Got: {visualize_tree(bst.root)}"
    )
    tree_2.root.left = None
    assert bst.root != tree_2.root

@points(0.25)
def test_insert_duplicates():
    bst = BinarySearchTree()
    bst.insert(key=1, value="1")
    with pytest.raises(KeyError):
        bst.insert(key=1, value="1")

@points(0.25)
def test_insert_with_size(tree_2: TreeSolution):
    bst = BinarySearchTree()
    for i, insert in enumerate(tree_2.insertion_order):
        assert bst.size == i
        bst.insert(*insert)
        assert bst.size == i + 1

@points(0.25)
def test_insert_duplicates_with_size(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)

    with pytest.raises(KeyError):
        bst.insert(key=1, value="1")
    assert bst.size == tree_2.size

@points(0.25)
def test_insert_none():
    bst = BinarySearchTree()
    with pytest.raises(TypeError):
        bst.insert(None, None) # type: ignore
    with pytest.raises(TypeError):
        bst.insert(key=None, value="1") # type: ignore

@points(1)
def test_depth(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    assert bst.find(5).depth == 0
    assert bst.find(18).depth == 1
    assert bst.find(1).depth == 1
    assert bst.find(8).depth == 2
    assert bst.find(3).depth == 2
    assert bst.find(14).depth == 3
    assert bst.find(13).depth == 4
    assert bst.find(16).depth == 4

@points(0.5)
def test_get_parent(tree_1: TreeSolution):
    bst = BinarySearchTree()
    for item in tree_1.insertion_order:
        bst.insert(*item)

    node_5 = bst.find(5)
    node_12 = bst.find(12)
    node_3 = bst.find(3)

    assert node_5.parent is not None
    assert node_12.parent is not None
    assert node_3.parent is not None
    assert node_5.parent.key == 10
    assert node_12.parent.key == 10
    assert node_3.parent.key == 5

    assert bst.find(10).parent is None

@points(1.5)
def test_find(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    for key, _ in tree_2.insertion_order:
        assert bst.find(key).key == key

@points(0.25)
def test_find_non_existing_key(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    with pytest.raises(KeyError):
        bst.find(2)
    with pytest.raises(KeyError):
        bst.find(21)
    with pytest.raises(KeyError):
        BinarySearchTree().find(12)
    
@points(0.25)
def test_find_invalid_key():
    bst = BinarySearchTree()
    with pytest.raises(TypeError):
        bst.find(None) # type: ignore

    with pytest.raises(TypeError):
        bst.find("12") # type: ignore

@points(4.5)
def test_remove(trees_while_deleting: tuple[TreeSolution, list[tuple[int, TreeNode | None]]]):
    bst = BinarySearchTree(trees_while_deleting[0].root, trees_while_deleting[0].size)
    assert bst.root != trees_while_deleting[1][1]
    for key_to_remove, expected_structure in trees_while_deleting[1]:
        bst.remove(key_to_remove)
        assert bst.root == expected_structure, (
            f"Invalid structure after deleting key {key_to_remove}\n"
            f"Expected: {visualize_tree(expected_structure)}"
            f"Got: {visualize_tree(bst.root)}"
        )
        

@points(0.25)
def test_remove_non_existing_key(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    with pytest.raises(KeyError):
        bst.remove(20)
    with pytest.raises(KeyError):
        BinarySearchTree().remove(2)

@points(0.25)
def test_remove_invalid_key():
    bst = BinarySearchTree()
    with pytest.raises(TypeError):
        bst.remove(None) # type: ignore
    with pytest.raises(TypeError):
        bst.remove("12") # type: ignore

@points(0.25)
def test_size_with_remove(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    bst.remove(1)
    assert bst.size == 7
    bst.remove(8)
    assert bst.size == 6
    bst.remove(5)
    assert bst.size == 5

@points(0.25)
def test_size_with_remove_non_existing(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    with pytest.raises(KeyError):
        bst.remove(20)
    assert bst.size == 8

@points(0.5)
def test_inorder(tree_1: TreeSolution, tree_2: TreeSolution):
    bst = BinarySearchTree(tree_1.root, tree_1.size)
    assert list(bst.inorder()) == tree_1.inorder
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    assert list(bst.inorder()) == tree_2.inorder

@points(0.5)
def test_preorder(tree_1: TreeSolution, tree_2: TreeSolution):
    bst = BinarySearchTree(tree_1.root, tree_1.size)
    assert list(bst.preorder()) == tree_1.preorder
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    assert list(bst.preorder()) == tree_2.preorder

@points(0.5)
def test_postorder(tree_1: TreeSolution, tree_2: TreeSolution):
    bst = BinarySearchTree(tree_1.root, tree_1.size)
    assert list(bst.postorder()) == tree_1.postorder
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    assert list(bst.postorder()) == tree_2.postorder

@points(1)
def test_runtime_comparison_assignment_example_check():

    result = BinarySearchTree.count_comparisons([8, 17, 10, 3, 1], 3)
    assert result[0] == 4
    assert result[1] == 3

@points(2)
@pytest.mark.timeout(10)
def test_runtime_comparison_check_with_pregen_list():
    try:
        test_list = create_list_from_file("testListWithoutDuplicates.txt")
    except FileNotFoundError:
        pytest.skip("testListWithoutDuplicates.txt not found")
    key = test_list[len(test_list) - 1]
    
    result = BinarySearchTree.count_comparisons(test_list, key)
    assert result[0] == len(test_list)
    assert result[1] == 53

@points(0.5)
def test_runtime_comparison_sorted_list():
    bst = BinarySearchTree()
    test_list = []
    num_keys = 10
    key = num_keys - 1

    for i in range(0, num_keys):
        test_list.append(i)
        bst.insert(key=i, value=str(i))
    result = BinarySearchTree.count_comparisons(list(range(num_keys)), key)

    assert result[1] == len(test_list) * 2 - 1
    assert result[0] == len(test_list)

@points(0.5)
def test_is_valid_true(tree_1: TreeSolution, tree_2: TreeSolution):
    bst = BinarySearchTree(tree_1.root, tree_1.size)
    assert bst.is_valid() is True
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    assert bst.is_valid() is True

@points(0.5)
def test_is_valid_false():
    root13 = TreeNode(key=13, value="13")
    node18 = TreeNode(key=18, value="18")
    root13.left = node18
    bst = BinarySearchTree(root13, 2)
    assert bst.is_valid() is False

    root13.left = TreeNode(key=5, value="5")
    root13.right = TreeNode(key=1, value="1")
    bst = BinarySearchTree(root13, 3)
    assert bst.is_valid() is False

@points(0.25)
def test_return_min_key(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    min_key = bst.return_min_key()
    assert min_key is not None
    assert min_key.key == 1

@points(0.25)
def test_return_max_key(tree_2: TreeSolution):
    bst = BinarySearchTree(tree_2.root, tree_2.size)
    max_key = bst.return_max_key()
    assert max_key is not None
    assert max_key.key == 18


if __name__ == "__main__":
    try:
        import pytest_timeout

        pytest_timeout_installed = True
        del sys.modules["pytest_timeout"]
    except ModuleNotFoundError:
        print(
            "Consider installing pytest-timeout to execute all tests even if some test hangs."
        )
        pytest_timeout_installed = False

    if pytest_timeout_installed:
        pytest.main([__file__, "-rA", "--timeout=2"])
    else:
        pytest.main([__file__, "-rA"])